" - PLUGINS -

call plug#begin('~/.vim/plugged')
	Plug 'scrooloose/syntastic'
	Plug 'mattn/emmet-vim'
	Plug 'neoclide/coc.nvim', {'branch': 'release'}
	Plug 'scrooloose/nerdcommenter'
	Plug 'drewtempelmeyer/palenight.vim'
	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
	Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
	Plug 'junegunn/fzf.vim'

call plug#end()

" - PLUGIN CONFIGURATION

filetype plugin indent on

call coc#add_extension('coc-html', 'coc-css')

if (has("nvim"))
"For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
	let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif
"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
	set termguicolors
endif

"---Airline---"
let g:airline_powerline_fonts = 1
let g:airline_theme = "palenight"
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#coc#enabled = 1

if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

" - CONFIGURATION -

"---basic things---"
set nocompatible
syntax enable
set noswapfile
set mouse=a
set hidden

"---wildmenu---"
set wildmenu
set showcmd
set wildignorecase

"---display---"
set cursorline
set scrolloff=10
set wrap
set linebreak
colorscheme palenight
set list
set listchars=tab:>-,trail:.

"---indent---"
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smartindent
set autoindent

" - FUNCTIONS -
function! PrintCC() "display a line at column 80
	if (&cc == 80)
		set cc=0
	else
		set cc=80
	endif
endfunc

" - SHORTCUTS -

let mapleader = ","
noremap <F8>		:call PrintCC()<CR>
noremap <S-t>		:enew<CR>
noremap <S-k>		:bprevious<CR>
noremap <S-j>		:bnext<CR>
noremap <leader>w	:bd<CR>
noremap <leader>n	:set relativenumber!<CR>
map <leader>/		<plug>NERDCommenterToggle
noremap <leader>p	:Files<CR>
noremap <leader>pp	:History<CR>
